/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CControlador_Cajero;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tinit
 */
public class interfazCajero extends javax.swing.JFrame {

    /**
     * Creates new form interfazCajero
     */
    DefaultTableModel modelo;
    CControlador_Cajero c = new CControlador_Cajero();

    public interfazCajero() {
        initComponents();

        modelo = (DefaultTableModel) tabla.getModel();
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);
        tabla.setGridColor(java.awt.Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_N2 = new javax.swing.JButton();
        B_LIMPIAR = new javax.swing.JButton();
        B_N3 = new javax.swing.JButton();
        B_N4 = new javax.swing.JButton();
        B_N5 = new javax.swing.JButton();
        B_N6 = new javax.swing.JButton();
        B_N7 = new javax.swing.JButton();
        B_N8 = new javax.swing.JButton();
        B_N9 = new javax.swing.JButton();
        L_CajeroAutomático = new javax.swing.JLabel();
        B_ENTER = new javax.swing.JButton();
        TF_Imprimir = new javax.swing.JTextField();
        B_CORREGIR = new javax.swing.JButton();
        B_N1 = new javax.swing.JButton();
        B_N0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        L_IDCajero = new javax.swing.JLabel();
        L_IDCliente = new javax.swing.JLabel();
        IDcajero = new javax.swing.JTextField();
        IDcliente = new javax.swing.JTextField();
        L_NumeroCuenta = new javax.swing.JLabel();
        nCuenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_N2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N2.setText("2");
        B_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N2ActionPerformed(evt);
            }
        });

        B_LIMPIAR.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_LIMPIAR.setText("LIMPIAR");
        B_LIMPIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LIMPIARActionPerformed(evt);
            }
        });

        B_N3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N3.setText("3");
        B_N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N3ActionPerformed(evt);
            }
        });

        B_N4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N4.setText("4");
        B_N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N4ActionPerformed(evt);
            }
        });

        B_N5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N5.setText("5");
        B_N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N5ActionPerformed(evt);
            }
        });

        B_N6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N6.setText("6");
        B_N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N6ActionPerformed(evt);
            }
        });

        B_N7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N7.setText("7");
        B_N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N7ActionPerformed(evt);
            }
        });

        B_N8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N8.setText("8");
        B_N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N8ActionPerformed(evt);
            }
        });

        B_N9.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N9.setText("9");
        B_N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N9ActionPerformed(evt);
            }
        });

        L_CajeroAutomático.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 36)); // NOI18N
        L_CajeroAutomático.setText("Cajero Automatico");

        B_ENTER.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_ENTER.setText("ENTER");
        B_ENTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ENTERActionPerformed(evt);
            }
        });

        TF_Imprimir.setEditable(false);
        TF_Imprimir.setColumns(2);
        TF_Imprimir.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N

        B_CORREGIR.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_CORREGIR.setText("CORREGIR");
        B_CORREGIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CORREGIRActionPerformed(evt);
            }
        });

        B_N1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N1.setText("1");
        B_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N1ActionPerformed(evt);
            }
        });

        B_N0.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        B_N0.setText("0");
        B_N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_N0ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Denominacion ", "Billetes disponibles", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        L_IDCajero.setText("ID Cajero: ");

        L_IDCliente.setText("ID Cliente: ");

        L_NumeroCuenta.setText("Numero Cuenta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(L_CajeroAutomático))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TF_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(B_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B_N4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(B_N7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(50, 50, 50)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(B_N0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_N8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_N5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_N2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(L_IDCajero)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(IDcajero, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(L_IDCliente)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(IDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(L_NumeroCuenta)
                                                .addGap(18, 18, 18)
                                                .addComponent(nCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(B_N3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_N6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_N9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(50, 50, 50)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(B_ENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_CORREGIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(B_LIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(L_CajeroAutomático)
                .addGap(27, 27, 27)
                .addComponent(TF_Imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_IDCajero)
                    .addComponent(IDcajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NumeroCuenta)
                    .addComponent(nCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_IDCliente)
                    .addComponent(IDcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B_N2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_N3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_N1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_ENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_CORREGIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_N6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_N4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_N5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_N9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_N8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_N7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_LIMPIAR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(B_N0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N2ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "2");
    }//GEN-LAST:event_B_N2ActionPerformed

    private void B_LIMPIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LIMPIARActionPerformed
        TF_Imprimir.setText("");
    }//GEN-LAST:event_B_LIMPIARActionPerformed

    private void B_N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N3ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "3");
    }//GEN-LAST:event_B_N3ActionPerformed

    private void B_N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N4ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "4");
    }//GEN-LAST:event_B_N4ActionPerformed

    private void B_N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N5ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "5");
    }//GEN-LAST:event_B_N5ActionPerformed

    private void B_N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N6ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "6");
    }//GEN-LAST:event_B_N6ActionPerformed

    private void B_N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N7ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "7");
    }//GEN-LAST:event_B_N7ActionPerformed

    private void B_N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N8ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "8");
    }//GEN-LAST:event_B_N8ActionPerformed

    private void B_N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N9ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "9");
    }//GEN-LAST:event_B_N9ActionPerformed

    private void B_ENTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ENTERActionPerformed
        if (IDcajero.getText().isEmpty() || IDcliente.getText().isEmpty() || nCuenta.getText().isEmpty()) {
            TF_Imprimir.setText("Los campos están vacios. Llénelos.");
        } else {
            int idCajero = Integer.parseInt(IDcajero.getText().trim());
            int idCliente = Integer.parseInt(IDcliente.getText().trim());
            int ncuenta = Integer.parseInt(nCuenta.getText().trim());
            int dinero = Integer.parseInt(TF_Imprimir.getText().trim());

            int retirar = c.retirarDinero(idCajero, ncuenta, idCajero, dinero);

            if (retirar == 0) {
                TF_Imprimir.setText("Error en el sql.");
            } else if (retirar == 10) {
                TF_Imprimir.setText(c.getResultadoCajero());

                modelo.setRowCount(0);
                HashMap<Integer, Integer> billetes = c.getCajero();

                int[] valores = {10000, 20000, 50000, 100000};
                for (int valor : valores) {
                    if (billetes.containsKey(valor)) {
                        modelo.addRow(new Object[]{valor, billetes.get(valor), valor * billetes.get(valor)});
                    }
                }
            } else if (retirar == 1) {
                TF_Imprimir.setText("El cliente no existe.");
            } else if (retirar == 3) {
                TF_Imprimir.setText("Saldo insuficiente.");
            } else if (retirar == 4) {
                TF_Imprimir.setText("El cajero no existe.");
            } else if (retirar == 8) {
                TF_Imprimir.setText("Monto no permitido, solo múltiplos de 10.000.");
            } else if (retirar == 7) {
                TF_Imprimir.setText("Monto no permitido, solo se puede entre 10.000 y 1.000.000.");
            } else if (retirar == 9) {
                TF_Imprimir.setText("No hay billetes suficientes para retirar.");
            } else if (retirar == 2) {
                TF_Imprimir.setText("El cliente está ocupado.");
            } else if (retirar == 5) {
                TF_Imprimir.setText("El cajero está ocupado.");
            } else if (retirar == 6) {
                TF_Imprimir.setText("Ingrese un valor entre 10.000 y 1.000.000.");
            } else {
                TF_Imprimir.setText("Ingrese los datos necesarios para retirar.");
            }
        }
    }//GEN-LAST:event_B_ENTERActionPerformed

    private void B_CORREGIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CORREGIRActionPerformed
        String corregir = TF_Imprimir.getText();

        if (corregir.length() > 0) {
            String corregido = corregir.substring(0, corregir.length() - 1);//crea una nueva cadena a partir de una existente.
            TF_Imprimir.setText(corregido);
        } //  Fin if
    }//GEN-LAST:event_B_CORREGIRActionPerformed

    private void B_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N1ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "1");
    }//GEN-LAST:event_B_N1ActionPerformed

    private void B_N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_N0ActionPerformed
        TF_Imprimir.setText(TF_Imprimir.getText() + "0");
    }//GEN-LAST:event_B_N0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_CORREGIR;
    private javax.swing.JButton B_ENTER;
    private javax.swing.JButton B_LIMPIAR;
    private javax.swing.JButton B_N0;
    private javax.swing.JButton B_N1;
    private javax.swing.JButton B_N2;
    private javax.swing.JButton B_N3;
    private javax.swing.JButton B_N4;
    private javax.swing.JButton B_N5;
    private javax.swing.JButton B_N6;
    private javax.swing.JButton B_N7;
    private javax.swing.JButton B_N8;
    private javax.swing.JButton B_N9;
    private javax.swing.JTextField IDcajero;
    private javax.swing.JTextField IDcliente;
    private javax.swing.JLabel L_CajeroAutomático;
    private javax.swing.JLabel L_IDCajero;
    private javax.swing.JLabel L_IDCliente;
    private javax.swing.JLabel L_NumeroCuenta;
    private javax.swing.JTextField TF_Imprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nCuenta;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
