/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import vista.interfazCajero;
import vista.interfazAdministracion;

/**
 *
 * @author tinit
 */
public class interfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form interfazPrincipal
     */
    public interfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_Titulo = new javax.swing.JLabel();
        L_PortalCajero = new javax.swing.JLabel();
        L_PortalAdministración = new javax.swing.JLabel();
        B_IngresarCajero = new javax.swing.JButton();
        B_IngresarAdministración = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        L_Titulo.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        L_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_Titulo.setText("Sistema Bancario - Banco Terra Prime");

        L_PortalCajero.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        L_PortalCajero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_PortalCajero.setText("Portal Cajero ");

        L_PortalAdministración.setFont(new java.awt.Font("Calisto MT", 0, 24)); // NOI18N
        L_PortalAdministración.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_PortalAdministración.setText("Portal Administración");

        B_IngresarCajero.setText("Ingresar Cajero");
        B_IngresarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IngresarCajeroActionPerformed(evt);
            }
        });

        B_IngresarAdministración.setText("Ingresar Administración");
        B_IngresarAdministración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IngresarAdministraciónActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(L_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_PortalCajero)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(B_IngresarCajero)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(B_IngresarAdministración)
                        .addGap(34, 34, 34))
                    .addComponent(L_PortalAdministración))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(L_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_PortalAdministración)
                        .addGap(34, 34, 34)
                        .addComponent(B_IngresarAdministración))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_PortalCajero)
                        .addGap(34, 34, 34)
                        .addComponent(B_IngresarCajero)))
                .addGap(0, 79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_IngresarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IngresarCajeroActionPerformed
        interfazCajero inter=new interfazCajero();
        inter.setVisible(true);
    }//GEN-LAST:event_B_IngresarCajeroActionPerformed

    private void B_IngresarAdministraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IngresarAdministraciónActionPerformed
        interfazAdministracion inter=new interfazAdministracion();
        inter.setVisible(true);
    }//GEN-LAST:event_B_IngresarAdministraciónActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_IngresarAdministración;
    private javax.swing.JButton B_IngresarCajero;
    private javax.swing.JLabel L_PortalAdministración;
    private javax.swing.JLabel L_PortalCajero;
    private javax.swing.JLabel L_Titulo;
    // End of variables declaration//GEN-END:variables
}
