/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CCajero;

/**
 *
 * @author tinit
 */
public class interfazAdministrarCajeros extends javax.swing.JFrame {

    // Modelo para manipular la tabla
    DefaultTableModel modelo;
    CControlador_Administracion ca = new CControlador_Administracion();

    /**
     * Creates new form interfazAdministrarCajeros
     */
    public interfazAdministrarCajeros() {
        initComponents();

        //inicio el modelo para manipular la tabla
        modelo = (DefaultTableModel) tabla.getModel();

        // Mostrar líneas de la tabla
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);

        // Color de las líneas
        tabla.setGridColor(java.awt.Color.BLACK);
    }

    private void limpiar() {
        ndiez.setText("");
        nveinte.setText("");
        ncincuenta.setText("");
        ncien.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        nveinte1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        B_EditarCajero = new javax.swing.JButton();
        B_AgregarCajero = new javax.swing.JButton();
        B_ConsultarCajero = new javax.swing.JButton();
        B_ConsignarCajero = new javax.swing.JButton();
        B_RetirarCajero = new javax.swing.JButton();
        B_BorrarCajero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        ndiez = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nveinte = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        ncincuenta = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        ncien = new javax.swing.JTextField();
        B_Volver = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        salidaCajero = new javax.swing.JTextArea();
        id = new javax.swing.JButton();
        idCajero = new javax.swing.JTextField();

        jButton3.setText("Billetes 20.000");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nveinte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nveinte1ActionPerformed(evt);
            }
        });

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_EditarCajero.setText("Editar cajero");
        B_EditarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditarCajeroActionPerformed(evt);
            }
        });

        B_AgregarCajero.setText("Agregar Cajero");
        B_AgregarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AgregarCajeroActionPerformed(evt);
            }
        });

        B_ConsultarCajero.setText("Consultar Cajero");
        B_ConsultarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ConsultarCajeroActionPerformed(evt);
            }
        });

        B_ConsignarCajero.setText("Consignar al cajero");

        B_RetirarCajero.setText("Retirar del cajero");

        B_BorrarCajero.setText("Borrar cajero");
        B_BorrarCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarCajeroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calisto MT", 0, 36)); // NOI18N
        jLabel1.setText("Administrar cajeros");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Billetes 10.000", "Billetes 20.000", "Billetes 50.000", "Billetes 100.000", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Billetes 10.000");

        ndiez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndiezActionPerformed(evt);
            }
        });

        jButton2.setText("Billetes 20.000");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nveinte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nveinteActionPerformed(evt);
            }
        });

        jButton4.setText("Billetes 50.000");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        ncincuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncincuentaActionPerformed(evt);
            }
        });

        jButton5.setText("Billetes 100.000");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ncien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncienActionPerformed(evt);
            }
        });

        B_Volver.setText("Volver");
        B_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_VolverActionPerformed(evt);
            }
        });

        salidaCajero.setColumns(20);
        salidaCajero.setRows(5);
        jScrollPane3.setViewportView(salidaCajero);

        id.setText("ID");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        idCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCajeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 213, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_ConsultarCajero)
                            .addComponent(B_ConsignarCajero))
                        .addGap(36, 36, 36)
                        .addComponent(B_RetirarCajero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_Volver))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(B_AgregarCajero)
                        .addGap(45, 45, 45)
                        .addComponent(B_BorrarCajero)
                        .addGap(49, 49, 49)
                        .addComponent(B_EditarCajero)))
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(ncincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(ndiez, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(nveinte, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(ncien, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(139, 139, 139))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(286, 286, 286))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(ndiez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(nveinte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(ncincuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(ncien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(idCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_ConsultarCajero)
                    .addComponent(B_AgregarCajero)
                    .addComponent(B_BorrarCajero)
                    .addComponent(B_EditarCajero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_ConsignarCajero)
                    .addComponent(B_RetirarCajero)
                    .addComponent(B_Volver))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_EditarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditarCajeroActionPerformed

        if (idCajero.getText().isEmpty() || ndiez.getText().isEmpty() || nveinte.getText().isEmpty() || ncincuenta.getText().isEmpty() || ncien.getText().isEmpty()) {
            salida.setText("Los campos estan vacios o incompletos. Llene todos los campos. ");
        } else {
            int id1 = Integer.parseInt(idCajero.getText());
            int diez = Integer.parseInt(ndiez.getText());
            int veinte = Integer.parseInt(nveinte.getText());
            int cincuenta = Integer.parseInt(ncincuenta.getText());
            int cien = Integer.parseInt(ncien.getText());
            boolean edit = ca.editarCajero(id1, diez, veinte, cincuenta, cien);
            if (edit) {
                salida.setText("El Cajero se ha editado correctamente.");
                limpiar();
            } else {
                salida.setText("Error editando Cajero.");
            }
        }
    }//GEN-LAST:event_B_EditarCajeroActionPerformed

    private void B_AgregarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AgregarCajeroActionPerformed

        int diez = Integer.parseInt(ndiez.getText());
        int veinte = Integer.parseInt(nveinte.getText());
        int cincuenta = Integer.parseInt(ncincuenta.getText());
        int cien = Integer.parseInt(ncien.getText());

        if (ndiez.getText().isEmpty() || nveinte.getText().isEmpty() || ncincuenta.getText().isEmpty() || ncien.getText().isEmpty()) {
            salidaCajero.setText("Los campos estan vacios o incompletos. Llene todos los campos. ");
        } else {
            boolean agre = ca.agregarCajero(diez, veinte, cincuenta, cien);
            if (agre) {
                salidaCajero.setText("El cajero se ha agregado correctamente.");
                limpiar();
            } else {
                salidaCajero.setText("Error agregando contacto.");
            }
        }
    }//GEN-LAST:event_B_AgregarCajeroActionPerformed

    private void B_ConsultarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ConsultarCajeroActionPerformed
        ArrayList<CCajero> lista = new ArrayList<>();
        lista = ca.consultarCajero();

        //limpio la tabla antes de llevar los valores
        modelo.setRowCount(0);

        for (CCajero con : lista) {
            modelo.addRow(new Object[]{con.getId(), con.getNdiez(), con.getNveinte(), con.getNcincuenta(), con.getNcien(), con.getEstado()});
        }
    }//GEN-LAST:event_B_ConsultarCajeroActionPerformed

    private void B_BorrarCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarCajeroActionPerformed
        int result = JOptionPane.showConfirmDialog(null, "Esta seguro de borrar este Cajero?", "Confirmar", JOptionPane.YES_NO_OPTION); // Buttons to display (e.g., Yes and No)

        int id = Integer.parseInt(idCajero.getText());
        if (idCajero.getText().isEmpty()) {
            salidaCajero.setText("No se ha ingresado un id ");
        } else {
            boolean borr = ca.borrarCajero(id);
            if (borr) {
                salidaCajero.setText("El Cajero se ha borrado correctamente.");
                limpiar();
            } else {
                salidaCajero.setText("Error borrando Cajero.");
            }
        }
    }//GEN-LAST:event_B_BorrarCajeroActionPerformed

    private void ndiezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndiezActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ndiezActionPerformed

    private void nveinteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nveinteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nveinteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nveinte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nveinte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nveinte1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ncincuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncincuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ncincuentaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ncienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ncienActionPerformed

    private void B_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_VolverActionPerformed
        // TODO add your handling code here:
        interfazAdministracion p = new interfazAdministracion();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_VolverActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void idCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCajeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAdministrarCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAdministrarCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAdministrarCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAdministrarCajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAdministrarCajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AgregarCajero;
    private javax.swing.JButton B_BorrarCajero;
    private javax.swing.JButton B_ConsignarCajero;
    private javax.swing.JButton B_ConsultarCajero;
    private javax.swing.JButton B_EditarCajero;
    private javax.swing.JButton B_RetirarCajero;
    private javax.swing.JButton B_Volver;
    private javax.swing.JButton id;
    private javax.swing.JTextField idCajero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField ncien;
    private javax.swing.JTextField ncincuenta;
    private javax.swing.JTextField ndiez;
    private javax.swing.JTextField nveinte;
    private javax.swing.JTextField nveinte1;
    private javax.swing.JTextArea salida;
    private javax.swing.JTextArea salidaCajero;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
