/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CControlador_Administracion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CCliente;
import vista.interfazAdministrarCajeros;
import vista.interfazPrincipal;

/**
 *
 * @author tinit
 */
public class interfazAdministracion extends javax.swing.JFrame {

    // Modelo para manipular la tabla
    DefaultTableModel modelo;
    CControlador_Administracion c = new CControlador_Administracion();

    /**
     * Creates new form interfazAdministracion
     */
    public interfazAdministracion() {
        initComponents();

        //inicio el modelo para manipular la tabla
        modelo = (DefaultTableModel) tabla.getModel();

        // Mostrar líneas de la tabla
        tabla.setShowHorizontalLines(true);
        tabla.setShowVerticalLines(true);

        // Color de las líneas
        tabla.setGridColor(java.awt.Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_BuscarPorNombre = new javax.swing.JButton();
        L_Id = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        B_BuscarPorID = new javax.swing.JButton();
        B_AgregarCliente = new javax.swing.JButton();
        B_ConsultarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        salida = new javax.swing.JTextArea();
        B_BorrarContacto = new javax.swing.JButton();
        L_Nombres = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        L_Apellidos = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        L_Telefono = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        L_Dirección = new javax.swing.JLabel();
        B_EditarCliente = new javax.swing.JButton();
        ncuenta = new javax.swing.JTextField();
        L_NumeroCuenta = new javax.swing.JLabel();
        saldo = new javax.swing.JTextField();
        L_NumeroCuenta1 = new javax.swing.JLabel();
        B_Consignar = new javax.swing.JButton();
        B_Retirar = new javax.swing.JButton();
        B_AdministrarCajeros = new javax.swing.JButton();
        B_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_BuscarPorNombre.setText("Buscar por nombre ");
        B_BuscarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BuscarPorNombreActionPerformed(evt);
            }
        });

        L_Id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Id.setText("ID:");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });

        B_BuscarPorID.setText("Buscar por ID");
        B_BuscarPorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BuscarPorIDActionPerformed(evt);
            }
        });

        B_AgregarCliente.setText("Agregar");
        B_AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AgregarClienteActionPerformed(evt);
            }
        });

        B_ConsultarCliente.setText("Consultar");
        B_ConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ConsultarClienteActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Telefono", "Ciudad", "Numero Cuenta", "Saldo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        salida.setColumns(20);
        salida.setRows(5);
        jScrollPane2.setViewportView(salida);

        B_BorrarContacto.setText("Borrar cliente");
        B_BorrarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BorrarContactoActionPerformed(evt);
            }
        });

        L_Nombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Nombres.setText("Nombres:");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        L_Apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Apellidos.setText("Apellidos:");

        apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoActionPerformed(evt);
            }
        });

        L_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Telefono.setText("Teléfono:");

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        L_Dirección.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_Dirección.setText("Ciudad:");

        B_EditarCliente.setText("Editar cliente");
        B_EditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_EditarClienteActionPerformed(evt);
            }
        });

        ncuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ncuentaActionPerformed(evt);
            }
        });

        L_NumeroCuenta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_NumeroCuenta.setText("Numero cuenta:");

        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });

        L_NumeroCuenta1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        L_NumeroCuenta1.setText("Saldo:");

        B_Consignar.setText("Consignar");
        B_Consignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ConsignarActionPerformed(evt);
            }
        });

        B_Retirar.setText("Retirar");
        B_Retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RetirarActionPerformed(evt);
            }
        });

        B_AdministrarCajeros.setText("ADMINISTRAR CAJEROS");
        B_AdministrarCajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AdministrarCajerosActionPerformed(evt);
            }
        });

        B_Volver.setText("Volver");
        B_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(L_Id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(B_BuscarPorID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(L_NumeroCuenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ncuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(B_ConsultarCliente)
                                    .addComponent(B_Consignar))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_Retirar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B_AgregarCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                        .addComponent(B_BorrarContacto)
                                        .addGap(27, 27, 27)
                                        .addComponent(B_EditarCliente)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(L_NumeroCuenta1)
                        .addGap(18, 18, 18)
                        .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(B_BuscarPorNombre)
                    .addComponent(B_AdministrarCajeros))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(B_Volver)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L_Nombres)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(L_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L_Dirección)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(L_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(151, 151, 151)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(47, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ncuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_NumeroCuenta)
                    .addComponent(L_NumeroCuenta1)
                    .addComponent(saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_Id)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B_BuscarPorID)))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_AgregarCliente)
                    .addComponent(B_ConsultarCliente)
                    .addComponent(B_BorrarContacto)
                    .addComponent(B_EditarCliente)
                    .addComponent(B_BuscarPorNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Consignar)
                    .addComponent(B_Retirar)
                    .addComponent(B_AdministrarCajeros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                .addComponent(B_Volver)
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_Nombres)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L_Apellidos)
                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(L_Telefono)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(L_Dirección)
                        .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Código para limpias los campos de texto
    private void limpiar() {
        nombre.setText("");
        apellido.setText("");
        telefono.setText("");
        ciudad.setText("");
        ncuenta.setText("");
        saldo.setText("");
    }

    private void B_BuscarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BuscarPorNombreActionPerformed
        limpiar();
        if (nombre.getText().isEmpty()) {
            salida.setText("El campo 'Nombre' está vacío. Ingrese un nombre");
        } else {
            ArrayList<CCliente> listaC = new ArrayList<>();
            listaC = c.consultarClientes();

            //limpio la tabla antes de llevar los valores
            modelo.setRowCount(0);

            for (CCliente con : listaC) {
                modelo.addRow(new Object[]{con.getId(), con.getNombre(), con.getApellido(), con.getTelefono(), con.getCiudad(), con.getNcuenta(), con.getSaldo(), con.getEstado()});
            }
        }

    }//GEN-LAST:event_B_BuscarPorNombreActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void B_BuscarPorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BuscarPorIDActionPerformed
        if (id.getText().isEmpty()) {
            salida.setText("El campo 'ID' esta vacío. Ingrese un ID");
        } else {
            CCliente cliente = c.buscarClienteID(Integer.parseInt(id.getText()));
            if (cliente != null) {
                // Con este código aparece el resultado en los campos de texto y así no se tiene que volver a escribir el cliente
                id.setText("" + cliente.getId()); // las dobles comillas son una conversión implícita = Integer.parseInt(id.getText())
                nombre.setText(cliente.getNombre());
                apellido.setText(cliente.getApellido());
                telefono.setText(cliente.getTelefono());
                ciudad.setText(cliente.getCiudad());
                ncuenta.setText("" + cliente.getNcuenta()); // las dobles comillas son una conversión implícita = Integer.parseInt(ncuenta.getText())
                saldo.setText("" + cliente.getSaldo()); // las dobles comillas son una conversión implícita = Integer.parseInt(saldo.getText())

                modelo.setRowCount(0);
                modelo.addRow(new Object[]{cliente.getId(), cliente.getNombre(), cliente.getApellido(), cliente.getTelefono(), cliente.getCiudad(), cliente.getNcuenta(), cliente.getSaldo()});

                salida.setText("ID: " + id.getText() + " encontrado."); // si lo de arriba se hizo, devuelve la salida correcta
            } else {
                salida.setText("No se encuentran ese ID. ");
            }
        }
    }//GEN-LAST:event_B_BuscarPorIDActionPerformed

    private void B_AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AgregarClienteActionPerformed

        if (nombre.getText().isEmpty() || apellido.getText().isEmpty() || telefono.getText().isEmpty() || ciudad.getText().isEmpty() || ncuenta.getText().isEmpty() || saldo.getText().isEmpty()) {
            salida.setText("Los campos estan vacios o incompletos. Llene todos los campos. ");
        } else {
            double sald = Integer.parseInt(saldo.getText()); // Se pone dentro del else para que no se le de un valor sin que se cumplan if.
            int cuenta = Integer.parseInt(ncuenta.getText()); // Se pone dentro del else para que no se le de un valor sin que se cumplan if.
            boolean agre = c.agregarClientes(nombre.getText(), apellido.getText(), telefono.getText(), ciudad.getText(), cuenta, sald);
            if (agre) {
                salida.setText("El cliente se ha agregado correctamente.");
                limpiar();
            } else {
                salida.setText("Error agregando contacto.");
            }
        }
    }//GEN-LAST:event_B_AgregarClienteActionPerformed

    private void B_ConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ConsultarClienteActionPerformed
        limpiar();
        ArrayList<CCliente> lista1 = new ArrayList<>();
        lista1 = c.consultarClientes();

        //limpio la tabla antes de llevar los valores
        modelo.setRowCount(0);

        for (CCliente con : lista1) {
            modelo.addRow(new Object[]{con.getId(), con.getNombre(), con.getApellido(), con.getTelefono(), con.getCiudad(), con.getNcuenta(), con.getSaldo(), con.getEstado()});
        }
    }//GEN-LAST:event_B_ConsultarClienteActionPerformed

    private void B_BorrarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BorrarContactoActionPerformed

        // Código para mostrar una ventana emergente de confirmación
        int result = JOptionPane.showConfirmDialog(null, "Esta seguro de borrar este cliente?", "Confirmar", JOptionPane.YES_NO_OPTION); // Buttons to display (e.g., Yes and No)

        int ide = Integer.parseInt(id.getText());
        if (result == JOptionPane.YES_OPTION) {
            if (id.getText().isEmpty()) {
                salida.setText("No se ha ingresado un ID ");
            } else {
                boolean borr = c.borrarCliente(ide);
                if (borr) {
                    salida.setText("El Cliente se ha borrado correctamente.");
                    limpiar();
                } else {
                    salida.setText("Error borrando Cliente.");
                }
            }
        }
    }//GEN-LAST:event_B_BorrarContactoActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void B_EditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_EditarClienteActionPerformed

        if (nombre.getText().isEmpty() || apellido.getText().isEmpty() || telefono.getText().isEmpty() || ciudad.getText().isEmpty() || ncuenta.getText().isEmpty() || saldo.getText().isEmpty()) {
            salida.setText("Los campos estan vacios o incompletos. Llene todos los campos. ");
        } else {
            int id1 = Integer.parseInt(id.getText());
            int cuenta = Integer.parseInt(ncuenta.getText());
            double sald = Double.parseDouble(saldo.getText());
            boolean edit = c.editarClientes(id1, nombre.getText(), apellido.getText(), telefono.getText(), ciudad.getText(), cuenta, sald);
            if (edit) {
                salida.setText("El Cliente se ha editado correctamente.");
                limpiar();
            } else {
                salida.setText("Error editando Cliente.");
            }
        }
    }//GEN-LAST:event_B_EditarClienteActionPerformed

    private void ncuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ncuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ncuentaActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void B_AdministrarCajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AdministrarCajerosActionPerformed
        interfazAdministrarCajeros inter = new interfazAdministrarCajeros();
        inter.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_AdministrarCajerosActionPerformed

    private void B_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_VolverActionPerformed
        // TODO add your handling code here:
        interfazPrincipal p = new interfazPrincipal();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_B_VolverActionPerformed

    private void B_ConsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ConsignarActionPerformed
        if (saldo.getText().isEmpty()) {
            salida.setText("El campo 'Saldo' está vacío. Llene el campo.");
        } else {

            int id1 = Integer.parseInt(id.getText());
            double valor = Double.parseDouble(saldo.getText());
            boolean consig = c.consignar(id1, valor);

            if (consig) {
                salida.setText("Al cliente se le han consignado: " + valor);
                limpiar();
            } else {
                salida.setText("Error consignando.");
            }
        }
    }//GEN-LAST:event_B_ConsignarActionPerformed

    private void B_RetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RetirarActionPerformed
        if (saldo.getText().isEmpty()) {
            salida.setText("Los campos están vacíos o incompletos. Llene todos los campos.");
        } else {
            int id1 = Integer.parseInt(id.getText());
            double valor = Double.parseDouble(saldo.getText());
            boolean consig = c.retirar(id1, valor);

            if (consig) {
                salida.setText("Al cliente se le han retirado: " + valor);
                limpiar();
            } else {
                salida.setText("Error retirando. El valor a retirar supera el valor disponible.");
            }
        }
    }//GEN-LAST:event_B_RetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AdministrarCajeros;
    private javax.swing.JButton B_AgregarCliente;
    private javax.swing.JButton B_BorrarContacto;
    private javax.swing.JButton B_BuscarPorID;
    private javax.swing.JButton B_BuscarPorNombre;
    private javax.swing.JButton B_Consignar;
    private javax.swing.JButton B_ConsultarCliente;
    private javax.swing.JButton B_EditarCliente;
    private javax.swing.JButton B_Retirar;
    private javax.swing.JButton B_Volver;
    private javax.swing.JLabel L_Apellidos;
    private javax.swing.JLabel L_Dirección;
    private javax.swing.JLabel L_Id;
    private javax.swing.JLabel L_Nombres;
    private javax.swing.JLabel L_NumeroCuenta;
    private javax.swing.JLabel L_NumeroCuenta1;
    private javax.swing.JLabel L_Telefono;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField id;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ncuenta;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextArea salida;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
